// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appBar': string;
  'buttonLogin': string;
  'link': string;
  'navbarLogin': string;
  'novLinks': string;
  'toolBar': string;
}
export const cssExports: CssExports;
export default cssExports;
