// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonLink': string;
  'descriptionTitle': string;
  'modal': string;
  'paper': string;
  'questionSingIn': string;
}
export const cssExports: CssExports;
export default cssExports;
